### ISSUE TITLE
Server-specified backoff is broken

### ISSUE THREAD

**Issue by nolanmar511** [GoogleCloudPlatform/cloud-profiler-nodejs#245]
Starting with `@google-cloud/common` 0.18.X, the response returned when there is an error is null, so we don't have the portion of the response needed to identify the server-specified backoff. 

I've filed https://github.com/googleapis/nodejs-common/issues/172

**Comment by nolanmar511** [comment]
We have not released in a while (~3 months), so this does not impact the released version of the agent.

**Comment by aalexand** [comment]
This seems like a serious issue. Any news on when it might be fixed?

**Comment by aalexand** [comment]
@nolanmar511 Looks like https://github.com/googleapis/nodejs-common/issues/172 is fixed so update the @google-cloud/common version?

**Comment by nolanmar511** [comment]
Been looking at this -- the change  googleapis/nodejs-common#182 does not fix this for us. Looking at the change, I believe it just returns the response field of the error as the response, and that response is missing the fields which specify the back off.
